name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure and Build APK
      run: |
        # root გაფრთხილების იგნორირება და ავტომატური ინიციალიზაცია
        buildozer --warn_on_root=0 init
        
        # პარამეტრების მოდიფიკაცია
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,txt/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        
        # Buildozer-ის გაშვება root გაფრთხილების გარეშე
        buildozer --warn_on_root=0 -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SmurfikApp-APK
        path: bin/*.apk
